# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_essay',
            name='essay_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Essay'),
            preserve_default=False,
        ),
    ]
