# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170325_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
