# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170325_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='due_time',
            field=models.DateField(default=2015),
        ),
    ]
