# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170325_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOffTopic', models.BooleanField()),
                ('Score', models.CharField(max_length=5)),
                ('error_list', jsonfield.fields.JSONField()),
                ('essay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Essay')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
