# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170327_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Score',
            new_name='score',
        ),
    ]
