# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170329_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
