# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170422_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='1', max_length=50, primary_key=True, serialize=False),
        ),
    ]
